version: '2.3'

services:
  codeception:
    build:
      context: .
      shm_size: '2gb'
    depends_on:
      - wordpress
    volumes:
      - ./:/project
      - wp-core:/wp-core
    entrypoint: /docker-entrypoint.sh
  wordpress:
    image: wordpress:latest
    depends_on:
      - mysql
      - chrome
    volumes:
      - wp-core:/var/www/html
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: wordpress

  mysql:
    image: mariadb:latest
    environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
    ports:
      - 3306:3306

  chrome:
    environment:
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
    volumes:
      - /dev/shm:/dev/shm
    image: selenium/standalone-chrome-debug:3.141.59-europium
    ports:
      - '4444'
      - '5900:5900'
volumes:
  wp-core: